// +build ignore
// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import goteamsnotify "go-teams-notify"
import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Send provides a mock function with given fields: webhookURL, webhookMessage
func (_m *Client) Send(webhookURL string, webhookMessage goteamsnotify.MessageCard) error {
	ret := _m.Called(webhookURL, webhookMessage)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, goteamsnotify.MessageCard) error); ok {
		r0 = rf(webhookURL, webhookMessage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
